/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import java.io.IOException;
import java.util.Arrays;
import java.util.stream.Collectors;
import java.util.UUID;
import ticket.booking.services.UserBookingService;
import ticket.booking.utils.UserServiceUtil;

public class App {
    public static void main(String[] args) {
        System.out.println("Running Train Booking System");
        Scanner sc=new Scanner(System.in);
        int option=0;
        UserBookingService userBookingService;
        try{
            userBookingService = new UserBookingService();
        }catch(IOException ex){
            System.out.println("There is some issue");
            return;
        }
        while(option!=7){
            System.out.println("Choose Option");
            System.out.println("1: Sign Up");
            System.out.println("2: Log In");
            System.out.println("3: Fetch Booking");
            System.out.println("4: Search Trains");
            System.out.println("5: Book a seat");
            System.out.println("6: Cancel My Booking");
            System.out.println("7: Exit the app");
            option=sc.nextInt();
            switch(option){
                case 1: 
                    System.out.println("Enter username to signUp");
                    String nameToSignUp=sc.next();
                    System.out.println("Enter The Password to signUp");
                    String passwordToSignUp=sc.next();
                    User userToSignUp=new User(nameToSignUp,passwordToSignUp,UserServiceUtil.hashPassword(passwordToSignUp),new ArrayList<>(),UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignUp);
                    break;
                case 2:
                    System.out.println("Enter Username to Login");
                    String nameToLogin=sc.next();
                    System.out.println("Enter the password to login");
                    String passwordtoLogin=sc.next();
                    User userToLogin=new User(nameToLogin,passwordToLogin,UserServiceUtil.hashPassword(passwordtoLogin),new ArrayList<>(),UUID.randomUUID().toString());
                    try{
                        userBookingService=new UserBookingService(userToLogin);
                    }catch(IOException e){
                        return;
                    }
                    break;
                case 3:
                    System.out.println("Fetching your bookings");
                    userBookingService.fetchBooking();
                    break;
                case 4:
                    System.out.println();
            }

        }
    }
}
