/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import java.util.Arrays;
import java.util.stream.Collectors;

public class App {
    public static void main(String[] args) {
        List<Integer> l=Arrays.asList(1,2,3,4,5,6,7,8,9,10);
        List<Integer> l1=l.stream().filter(e->e%2==0).collect(Collectors.toList());
        //when printed gives 2,4,6,8,10
        //in java function are first class parameters
        l.stream().map(e->e*2).collect(Collectors.asList());
    }
}
